# Site settings
title: Website Style Guide Resources
description: A collaborative collection of resources for creating Front-End Style Guides and Pattern Libraries
baseurl: ""
permalink: pretty

# Config
exclude: [README.md, Gemfile, Gemfile.lock, "vendor"]
gems:
    - jekyll-redirect-from

# Build settings
markdown: kramdown
